# Generated by Django 3.2.7 on 2021-12-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('hero', models.CharField(max_length=60)),
                ('agi_winrate', models.FloatField(null=True)),
                ('agi_pickorder', models.FloatField(null=True)),
                ('int_winrate', models.FloatField(null=True)),
                ('int_pickorder', models.FloatField(null=True)),
                ('str_winrate', models.FloatField(null=True)),
                ('str_pickorder', models.FloatField(null=True)),
                ('melee_winrate', models.FloatField(null=True)),
                ('melee_pickorder', models.FloatField(null=True)),
                ('ranged_winrate', models.FloatField(null=True)),
                ('ranged_pickorder', models.FloatField(null=True)),
                ('total_winrate', models.FloatField(null=True)),
                ('avg_pickorder', models.FloatField(null=True)),
                ('image', models.CharField(max_length=60, null=True)),
            ],
        ),
    ]
