# Generated by Django 3.2.7 on 2021-11-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='image',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ability',
            name='melee_pickorder',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ability',
            name='melee_winrate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ability',
            name='ranged_pickorder',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ability',
            name='ranged_winrate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ability',
            name='agi_pickorder',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ability',
            name='agi_winrate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ability',
            name='int_pickorder',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ability',
            name='int_winrate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ability',
            name='str_pickorder',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ability',
            name='str_winrate',
            field=models.FloatField(null=True),
        ),
    ]
