# Generated by Django 3.2.7 on 2022-01-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability_1_name', models.CharField(max_length=60)),
                ('ability_1_image', models.CharField(max_length=60, null=True)),
                ('ability_1_hero', models.CharField(max_length=60)),
                ('ability_1_winrate', models.FloatField(null=True)),
                ('ability_2_name', models.CharField(max_length=60)),
                ('ability_2_image', models.CharField(max_length=60, null=True)),
                ('ability_2_hero', models.CharField(max_length=60)),
                ('ability_2_winrate', models.FloatField(null=True)),
                ('total_winrate', models.FloatField(null=True)),
                ('synergy', models.FloatField(null=True)),
            ],
        ),
    ]
