# Generated by Django 3.2.7 on 2022-05-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_abilitycombo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('winrate', models.FloatField(null=True)),
                ('image', models.CharField(max_length=60, null=True)),
            ],
        ),
    ]
