# Generated by Django 3.2.7 on 2022-05-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='abilitycombo',
            name='native',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='abilitycombo',
            name='sample',
            field=models.IntegerField(null=True),
        ),
    ]
