# Generated by Django 3.2.7 on 2022-06-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_auto_20220518_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='agi_gain',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='agi_start',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='attack_point',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='attack_range',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='base_armor',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='base_attack_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='base_hps',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='base_mps',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='ias_start',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='int_gain',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='int_start',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='movement_speed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='primary_stat',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='projectile_speed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='ranged_flag',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='special_stats',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='str_gain',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='str_start',
            field=models.FloatField(null=True),
        ),
    ]
