# Generated by Django 3.2.7 on 2022-06-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_auto_20220603_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='range_string',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
