# Generated by Django 3.2.7 on 2022-06-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_hero_range_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='agi_string',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='int_string',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='str_string',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
